language: objective-c
osx_image: xcode9.1
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - WORKSPACE=WaveProgressView.xcworkspace
  - IOS_FRAMEWORK_SCHEME="WaveProgressView"
  - EXAMPLE_SCHEME="Example"
  - DESTINATION='platform=iOS Simulator,name=iPhone 6S'
script:
  - set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -destination "$DESTINATION" | xcpretty
